{{- if .Values.services }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: www-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    name: www-ingress
    tier: frontend
    release: {{ $.Values.release }}
  annotations:
    ingress.kubernetes.io/priority: "2"
    ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      {{- range $service := .Values.services }}
      {{- $_ := set $ "service" (merge dict $service) }}
      {{- if and $service.enabled $service.ingress.enabled }}
      - path: /{{ template "path-name" $ }}
        backend:
          serviceName: {{ template "service-name" $.service }}
          servicePort: {{  $service.ingress.port }}
      {{- end }}
      {{- end }}
    {{- if .Values.host }}
    host: {{ .Values.host }}
    {{- end }}
{{- end }}
