{{- $_ := set $ "service" (merge dict .Values.services.webhook) }}
{{- range $version, $image := $.service.version }}
{{- $_ := set $.service "tag" $image.tag }}
{{- $_ := set $.service "version" $version }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "configmap.labels" $ }}
data:
{{- end }}
