{{- $_ := set $ "service" (merge dict .Values.services.webhook) }}
{{- range $version, $image := $.service.version }}
{{- $_ := set $.service "tag" $image.tag }}
{{- $_ := set $.service "version" $version }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  {{- include "secret.labels" $ }}
data:
  CHANNEL_ACCESS_TOKEN: MWZURWdJOUhqS1YzUGZWTGhvTk1FTVp3RFBFRjFabStBM3RoUWdEOXBmc0lRT0YxWUxPWHZwMEtTQnQvMmk2UWk0cWgzWUh4MTJFbW5MdWhVcVhIUXVnbWloNm41MDk2K0w2Q0N1Rk9GRHVmNUhDU3d6UnVZTFhjTXNtRlpGdXpTYVdxeVRSMVlGNXZoRk1GbFNiVUZGR1VZaFdRZmVZOHNMR1JYZ28zeHZ3PQ==
  CHANNEL_SECRET: YmU2YTZiYjUwNjc5NDg2OWE2N2IxOTAwYTlhYTI0OWE=
  RABBIT_MQ_URL: YW1xcDovL2FkbWluOjFxMnczZTRyQHJhYmJpdG1xLWhlYWRsZXNzLnJhYmJpdG1xLnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI=
{{- end }}
